
version: '3.0'
services:
  web:
    image: jaczajka/io-lab-docker-ci-public:latest
    ports:
      - "5000:5000"
    depends_on:
      - "redis"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:6.0-rc3
    # TODO: persistence for redis. You need to persist /data directory.    
    volumes:
      - /home/jakub/Documents/redis:/data:z
